baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Group Coordinator'
theme = "relearn"

customCSS = ["/css/custom.css"] 

[params]
  [[params.themeVariant]]
    identifier = 'light'

  [[params.themeVariant]]
    identifier = 'dark'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true